
### GET /

GET http://localhost:3000/


### GET /items

GET http://localhost:3000/books


### GET items/:id

GET http://localhost:3000/books/13

### POST

POST http://localhost:3000/books/
content-type: application/json

{
    "name": "The Power and the Glory",
    "author": "Graham Greene",
    "language": "English",
    "pages": 222,
    "status": "want to read"
}


### PUT 

PUT http://localhost:3000/books/12
content-type: application/json

{"status": "read"}

### DELETE

DELETE http://localhost:3000/books/6