

### GET /

GET http://localhost:3000/


### GET /api/media

GET http://localhost:3000/api/media


### GET /api/media/:id

GET http://localhost:3000/api/media/9592

### POST

POST http://localhost:3000/api/media
content-type: application/json

{
  "filename": "60ac.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}


### PUT 

PUT http://localhost:3000/api/media/9590
content-type: application/json

{
  "title": "Basement modified",
  "description": "Some new description"
}

### DELETE

DELETE http://localhost:3000/api/media/